Repository Azure/azure-mcp, pull requests merged in 2025-04, with the labels that each got.

#41 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#51 Add DynamicallyAccessedMember annotations for AOT
  src/Commands/AppConfig/BaseAppConfigCommand.cs
  src/Commands/AppConfig/KeyValue/BaseKeyValueCommand.cs
  src/Commands/Cosmos/BaseCosmosCommand.cs
  src/Commands/Cosmos/BaseDatabaseCommand.cs
  src/Commands/GlobalCommand.cs
  src/Commands/IBaseCommand.cs
  src/Commands/Monitor/BaseMonitorCommand.cs
  src/Commands/Storage/BaseStorageCommand.cs
  src/Commands/Storage/Blob/Container/BaseContainerCommand.cs
  src/Commands/Subscription/BaseSubscriptionCommand.cs
  src/Commands/SubscriptionCommand.cs
Labels: bug

#49 Add aka.ms error message. Return suggested values
  src/Commands/BaseCommand.cs
  src/Commands/Server/ToolOperations.cs
  tests/Commands/Cosmos/AccountListCommandTests.cs
Labels: bug

#65 Create 01_onboard_request.yml
  .github/ISSUE_TEMPLATE/01_onboard_request.yml
Labels: Central-EngSys

#69 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#66 Add common workflows
  .github/event-processor.config
  .github/workflows/event-processor.yml
  .github/workflows/event.yml
  .github/workflows/post-apiview.yml
  .github/workflows/scheduled-event-processor.yml
Labels: Central-EngSys

#75 Bump to 0.0.11
  src/AzureMcp.csproj
Labels: Central-EngSys

#74 Create CHANGELOG.md
  CHANGELOG.md
  eng/scripts/Update-Version.ps1
  src/AzureMcp.csproj
Labels: documentation

#63 refactor finding cli path
  src/Commands/Extension/AzCommand.cs
Labels: area-AzCLI

#16 Add Dockerfile
  Dockerfile
  eng/npm/wrapper/package-lock.json
Labels: enhancement
