Repository Azure/azure-mcp, pull requests merged in 2025-05, with the labels that each got.

#61 Allow Azmcp to grab auth session from VS Code
  src/AzureMcp.csproj
  src/Helpers/EnvironmentVariableHelpers.cs
  src/Services/Azure/Authentication/CustomChainedCredential.cs
  src/Services/Azure/Authentication/WindowHandleProvider.cs
  tests/Services/Azure/Authentication/AuthenticationIntegrationTests.cs
Labels: enhancement

#87 Update ModelContextProtocol to 0.1.0-preview.11
  src/AzureMcp.csproj
  tests/Client/ClientToolTests.cs
  tests/Client/Helpers/CustomTestTransport.cs
Labels: customer-reported, community contribution

#83 Add Azure AI Search
  README.md
  src/Arguments/Search/BaseSearchArguments.cs
  src/Arguments/Search/Index/BaseIndexArguments.cs
  src/Arguments/Search/Index/IndexDescribeArguments.cs
  src/Arguments/Search/Index/IndexListArguments.cs
  src/Arguments/Search/Index/IndexQueryArguments.cs
  src/Arguments/Search/Service/ServiceListArguments.cs
  src/AzureMcp.csproj
  src/Commands/CommandFactory.cs
  src/Commands/Search/Index/IndexDescribeCommand.cs
  src/Commands/Search/Index/IndexListCommand.cs
  src/Commands/Search/Index/IndexQueryCommand.cs
  src/Commands/Search/Service/ServiceListCommand.cs
  src/Commands/Server/ServiceStartCommand.cs
  src/Models/Argument/ArgumentDefinitions.cs
  src/Program.cs
  src/Services/Azure/Search/SearchService.cs
  src/Services/Azure/Tenant/TenantService.cs
  src/Services/Interfaces/ISearchService.cs
  tests/Client/MockClientTests.cs
  tests/Commands/Search/Index/IndexDescribeCommandTests.cs
  tests/Commands/Search/Index/IndexListCommandTests.cs
  tests/Commands/Search/Index/IndexQueryCommandTests.cs
  tests/Commands/Search/Service/ServiceListCommandTests.cs
Labels: customer-reported, community contribution

#52 Use source-generated JSON serialization
  src/AzureMcp.csproj
  src/Commands/AppConfig/Account/AccountListCommand.cs
  src/Commands/AppConfig/AppConfigJsonContext.cs
  src/Commands/AppConfig/BaseAppConfigCommand.cs
  src/Commands/AppConfig/KeyValue/KeyValueDeleteCommand.cs
  src/Commands/AppConfig/KeyValue/KeyValueListCommand.cs
  src/Commands/AppConfig/KeyValue/KeyValueLockCommand.cs
  src/Commands/AppConfig/KeyValue/KeyValueSetCommand.cs
  src/Commands/AppConfig/KeyValue/KeyValueShowCommand.cs
  src/Commands/AppConfig/KeyValue/KeyValueUnlockCommand.cs
  src/Commands/BaseCommand.cs
  src/Commands/CommandFactory.cs
  src/Commands/Cosmos/AccountListCommand.cs
  src/Commands/Cosmos/BaseContainerCommand.cs
  src/Commands/Cosmos/ContainerListCommand.cs
  src/Commands/Cosmos/CosmosJsonContext.cs
  src/Commands/Cosmos/DatabaseListCommand.cs
  src/Commands/Cosmos/ItemQueryCommand.cs
  src/Commands/Extension/AzCommand.cs
  src/Commands/Extension/AzdCommand.cs
  src/Commands/Group/GroupListCommand.cs
  src/Commands/JsonSourceGenerationContext.cs
  src/Commands/Monitor/Log/LogQueryCommand.cs
  src/Commands/Monitor/MonitorJsonContext.cs
  src/Commands/Monitor/Table/TableListCommand.cs
  src/Commands/Monitor/Workspace/WorkspaceListCommand.cs
  src/Commands/Search/Index/IndexDescribeCommand.cs
  src/Commands/Search/Index/IndexListCommand.cs
  src/Commands/Search/Index/IndexQueryCommand.cs
  src/Commands/Search/SearchJsonContext.cs
  src/Commands/Search/Service/ServiceListCommand.cs
  src/Commands/Server/ToolOperations.cs
  src/Commands/Storage/Account/AccountListCommand.cs
  src/Commands/Storage/BaseStorageCommand.cs
  src/Commands/Storage/Blob/BlobListCommand.cs
  src/Commands/Storage/Blob/Container/BaseContainerCommand.cs
  src/Commands/Storage/Blob/Container/ContainerDetailsCommand.cs
  src/Commands/Storage/Blob/Container/ContainerListCommand.cs
  src/Commands/Storage/StorageJsonContext.cs
  src/Commands/Storage/Table/TableListCommand.cs
  src/Commands/Subscription/SubscriptionJsonContext.cs
  src/Commands/Subscription/SubscriptionListCommand.cs
  src/Commands/Tools/ToolsListCommand.cs
  src/Models/Argument/ArgumentBuilder.cs
  src/Models/Command/CommandResponse.cs
  src/Models/ModelsJsonContext.cs
  src/Program.cs
  src/Services/Azure/Cosmos/CosmosService.cs
  src/Services/Azure/Monitor/MonitorService.cs
  src/Services/Azure/Search/SearchService.cs
  src/Services/Interfaces/ICosmosService.cs
  src/Services/Interfaces/IMonitorService.cs
  src/Services/Interfaces/ISearchService.cs
  src/Services/ProcessExecution/ExternalProcessService.cs
  src/Services/ServicesJsonContext.cs
  tests/Commands/Search/Index/IndexDescribeCommandTests.cs
  tests/Commands/Search/Index/IndexQueryCommandTests.cs
Labels: enhancement

#93 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
Labels: Central-EngSys

#101 Fix casing in app-config live test
  src/AzureMcp.csproj
  tests/Client/AppConfigCommandTests.cs
Labels: test issue

#108 Add link to live tests instructions
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#81 Adds support for Azure Database for PostgreSQL
  Directory.Packages.props
  README.md
  docs/azmcp-commands.md
  src/Arguments/Postgres/BasePostgresArguments.cs
  src/Arguments/Postgres/Database/DatabaseListArguments.cs
  src/Arguments/Postgres/Database/DatabaseQueryArguments.cs
  src/Arguments/Postgres/Server/GetConfigArguments.cs
  src/Arguments/Postgres/Server/GetParamArguments.cs
  src/Arguments/Postgres/Server/ServerListArguments.cs
  src/Arguments/Postgres/Table/GetSchemaArguments.cs
  src/Arguments/Postgres/Table/TableListArguments.cs
  src/AzureMcp.csproj
  src/Commands/CommandFactory.cs
  src/Commands/Postgres/BaseDatabaseCommand.cs
  src/Commands/Postgres/BasePostgresCommand.cs
  src/Commands/Postgres/BaseServerCommand.cs
  src/Commands/Postgres/Database/DatabaseListCommand.cs
  src/Commands/Postgres/Database/DatabaseQueryCommand.cs
  src/Commands/Postgres/PostgresJsonContext.cs
  src/Commands/Postgres/Server/GetConfigCommand.cs
  src/Commands/Postgres/Server/GetParamCommand.cs
  src/Commands/Postgres/Server/ServerListCommand.cs
  src/Commands/Postgres/Table/GetSchemaCommand.cs
  src/Commands/Postgres/Table/TableListCommand.cs
  src/Models/Argument/ArgumentDefinitions.cs
  src/Program.cs
  src/Services/Azure/Postgres/PostgresService.cs
  src/Services/Interfaces/IPostgresService.cs
  tests/Commands/Postgres/Database/DatabaseListCommandTests.cs
  tests/Commands/Postgres/Database/DatabaseQueryCommandTests.cs
  tests/Commands/Postgres/Server/GetConfigCommandTests.cs
  tests/Commands/Postgres/Server/GetParamCommandTests.cs
  tests/Commands/Postgres/Server/ServerListCommandTests.cs
  tests/Commands/Postgres/Table/GetSchemaCommandTests.cs
  tests/Commands/Postgres/Table/TableListCommandTests.cs
Labels: customer-reported, community contribution

#105 Add AADSTS500200 error section in TROUBLESHOOTING
  TROUBLESHOOTING.md
Labels: documentation

#21 [ONBOARD] Kusto Add DataExplorer Operations
  .vscode/launch.json
  Directory.Packages.props
  README.md
  docs/azmcp-commands.md
  src/Arguments/Kusto/BaseClusterArguments.cs
  src/Arguments/Kusto/BaseDatabaseArguments.cs
  src/Arguments/Kusto/BaseTableArguments.cs
  src/Arguments/Kusto/ClusterGetArguments.cs
  src/Arguments/Kusto/ClusterListArguments.cs
  src/Arguments/Kusto/DatabaseListArguments.cs
  src/Arguments/Kusto/QueryArguments.cs
  src/Arguments/Kusto/SampleArguments.cs
  src/Arguments/Kusto/TableListArguments.cs
  src/Arguments/Kusto/TableSchemaArguments.cs
  src/AzureMcp.csproj
  src/Commands/CommandFactory.cs
  src/Commands/Kusto/BaseClusterCommand.cs
  src/Commands/Kusto/BaseDatabaseCommand.cs
  src/Commands/Kusto/BaseQueryCommand.cs
  src/Commands/Kusto/BaseSampleCommand.cs
  src/Commands/Kusto/BaseTableCommand.cs
  src/Commands/Kusto/ClusterGetCommand.cs
  src/Commands/Kusto/ClusterListCommand.cs
  src/Commands/Kusto/DatabaseListCommand.cs
  src/Commands/Kusto/KustoJsonContext.cs
  src/Commands/Kusto/QueryCommand.cs
  src/Commands/Kusto/SampleCommand.cs
  src/Commands/Kusto/TableListCommand.cs
  src/Commands/Kusto/TableSchemaCommand.cs
  src/Models/Argument/ArgumentDefinitions.cs
  src/Program.cs
  src/Services/Azure/Kusto/KustoService.cs
  src/Services/Interfaces/IKustoService.cs
  tests/Commands/Kusto/ClusterGetCommandTests.cs
  tests/Commands/Kusto/ClusterListCommandTests.cs
  tests/Commands/Kusto/DatabaseListCommandTests.cs
  tests/Commands/Kusto/QueryCommandTests.cs
  tests/Commands/Kusto/SampleCommandTests.cs
  tests/Commands/Kusto/TableListCommandTests.cs
  tests/Commands/Kusto/TableSchemaCommandTests.cs
Labels: onboarding

#127 Add Kusto to CHANGELOG.md
  CHANGELOG.md
Labels: area-Kusto

#128 Add Kusto service team to CODEOWNERS
  .github/CODEOWNERS
Labels: Central-EngSys, area-Kusto

#143 Fix formatting and clarify product names in azmcp-commands.md
  docs/azmcp-commands.md
Labels: documentation, customer-reported

#137 Conditionally set the TenantId property in DefaultAzureCredentialOptions
  src/Services/Azure/Authentication/CustomChainedCredential.cs
Labels: customer-reported, community contribution

#161 Update to ModelContextProtocol 0.1.0-preview.13
  CHANGELOG.md
  Directory.Packages.props
  tests/Client/ClientToolTests.cs
Labels: customer-reported, community contribution

#166 Move dotnet format check to build step
  CONTRIBUTING.md
  eng/pipelines/templates/common.yml
  eng/pipelines/templates/jobs/analyze.yml
  eng/scripts/Analyze-Code.ps1
  eng/scripts/Install-GitHooks.ps1
  eng/scripts/Remove-GitHooks.ps1
  src/AzureMcp.csproj
Labels: Central-EngSys

#165 Add instructions for auth in a dockerfile
  .gitignore
  README.md
Labels: area-Docker

#171 Add node pre-req to Readme
  README.md
Labels: documentation

#187 Add CODEOWNERS to steps for adding a new command
  .vscode/cspell.json
  CONTRIBUTING.md
Labels: documentation

#186 Update best practices docs
  .github/CODEOWNERS
  .vscode/cspell.json
  README.md
  docs/azmcp-commands.md
Labels: documentation, area-AzureAgent

#181 Auto-set labels and project reference for issues created with the Onboarding template
  .github/ISSUE_TEMPLATE/01_onboard_request.yml
  .vscode/cspell.json
Labels: Central-EngSys

#202 Add includeManaged in KeyVault list keys
  CHANGELOG.md
  docs/azmcp-commands.md
  src/Arguments/KeyVault/Key/KeyListArgument.cs
  src/Commands/KeyVault/Key/KeyListCommand.cs
  src/Models/Argument/ArgumentDefinitions.cs
  src/Services/Azure/KeyVault/KeyVaultService.cs
  src/Services/Interfaces/IKeyVaultService.cs
Labels: area-KeyVault

#206 Prepare hotfix release 0.0.18
  CHANGELOG.md
  docs/azmcp-commands.md
  src/Arguments/KeyVault/Key/KeyListArgument.cs
  src/AzureMcp.csproj
  src/Commands/KeyVault/Key/KeyListCommand.cs
  src/Models/Argument/ArgumentDefinitions.cs
  src/Services/Azure/KeyVault/KeyVaultService.cs
  src/Services/Interfaces/IKeyVaultService.cs
Labels: area-KeyVault

#214 Add Tool Titles and Refactor Command
  src/Commands/AppConfig/Account/AccountListCommand.cs
  src/Commands/AppConfig/KeyValue/KeyValueDeleteCommand.cs
  src/Commands/AppConfig/KeyValue/KeyValueListCommand.cs
  src/Commands/AppConfig/KeyValue/KeyValueLockCommand.cs
  src/Commands/AppConfig/KeyValue/KeyValueSetCommand.cs
  src/Commands/AppConfig/KeyValue/KeyValueShowCommand.cs
  src/Commands/AppConfig/KeyValue/KeyValueUnlockCommand.cs
  src/Commands/AzureBestPractices/AzureBestPracticesGetCommand.cs
  src/Commands/BaseCommand.cs
  src/Commands/Cosmos/AccountListCommand.cs
  src/Commands/Cosmos/ContainerListCommand.cs
  src/Commands/Cosmos/DatabaseListCommand.cs
  src/Commands/Cosmos/ItemQueryCommand.cs
  src/Commands/Extension/AzCommand.cs
  src/Commands/Extension/AzdCommand.cs
  src/Commands/Group/GroupListCommand.cs
  src/Commands/IBaseCommand.cs
  src/Commands/KeyVault/Key/KeyCreateCommand.cs
  src/Commands/KeyVault/Key/KeyGetCommand.cs
  src/Commands/KeyVault/Key/KeyListCommand.cs
  src/Commands/Kusto/ClusterGetCommand.cs
  src/Commands/Kusto/ClusterListCommand.cs
  src/Commands/Kusto/DatabaseListCommand.cs
  src/Commands/Kusto/QueryCommand.cs
  src/Commands/Kusto/SampleCommand.cs
  src/Commands/Kusto/TableListCommand.cs
  src/Commands/Kusto/TableSchemaCommand.cs
  src/Commands/Monitor/Log/LogQueryCommand.cs
  src/Commands/Monitor/Table/TableListCommand.cs
  src/Commands/Monitor/TableType/TableTypeListCommand.cs
  src/Commands/Monitor/Workspace/WorkspaceListCommand.cs
  src/Commands/Postgres/BaseDatabaseCommand.cs
  src/Commands/Postgres/BaseServerCommand.cs
  src/Commands/Postgres/Database/DatabaseListCommand.cs
  src/Commands/Postgres/Database/DatabaseQueryCommand.cs
  src/Commands/Postgres/Server/GetConfigCommand.cs
  src/Commands/Postgres/Server/GetParamCommand.cs
  src/Commands/Postgres/Server/ServerListCommand.cs
  src/Commands/Postgres/Table/GetSchemaCommand.cs
  src/Commands/Postgres/Table/TableListCommand.cs
  src/Commands/Search/Index/IndexDescribeCommand.cs
  src/Commands/Search/Index/IndexListCommand.cs
  src/Commands/Search/Index/IndexQueryCommand.cs
  src/Commands/Search/Service/ServiceListCommand.cs
  src/Commands/Server/ServiceStartCommand.cs
  src/Commands/ServiceBus/Queue/QueueDetailsCommand.cs
  src/Commands/ServiceBus/Queue/QueuePeekCommand.cs
  src/Commands/ServiceBus/Topic/SubscriptionDetailsCommand.cs
  src/Commands/ServiceBus/Topic/SubscriptionPeekCommand.cs
  src/Commands/ServiceBus/Topic/TopicDetailsCommand.cs
  src/Commands/Storage/Account/AccountListCommand.cs
  src/Commands/Storage/Blob/BlobListCommand.cs
  src/Commands/Storage/Blob/Container/ContainerDetailsCommand.cs
  src/Commands/Storage/Blob/Container/ContainerListCommand.cs
  src/Commands/Storage/Table/TableListCommand.cs
  src/Commands/Subscription/SubscriptionListCommand.cs
  src/Commands/Tools/ToolsListCommand.cs
  src/Docs/new-command.md
Labels: area-BestPractices

#201 Sync eng/common directory with azure-sdk-tools repository
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/README.md
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/TestResources-Helpers.ps1
  eng/common/TestResources/Update-TestResources.ps1
  eng/common/mcp/README.md
  eng/common/mcp/azure-sdk-mcp.ps1
  eng/common/pipelines/templates/archetype-typespec-emitter.yml
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  eng/common/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
  eng/common/pipelines/templates/steps/publish-1es-artifact.yml
  eng/common/pipelines/templates/steps/save-package-properties.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
  eng/common/pipelines/templates/steps/verify-links.yml
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Delete-RemoteTag.ps1
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
  eng/common/scripts/Helpers/AzSdkTool-Helpers.ps1
  eng/common/scripts/Helpers/git-helpers.ps1
  eng/common/scripts/Helpers/git-helpers.tests.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Test-SampleMetadata.ps1
  eng/common/scripts/Verify-Links.ps1
  eng/common/scripts/common.ps1
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/logging.ps1
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
  eng/common/testproxy/install-test-proxy.ps1
  eng/common/testproxy/target_version.txt
  eng/common/testproxy/test-proxy-standalone-tool.yml
  eng/common/testproxy/test-proxy-tool.yml
  eng/common/testproxy/test-proxy.ps1
Labels: Do Not Merge

#220 Update ModelContextProtocol to 0.2.0-preview.1
  CHANGELOG.md
  Directory.Packages.props
  src/Commands/Server/ServiceStartCommand.cs
  src/Commands/Server/ToolOperations.cs
  tests/Client/ClientToolTests.cs
  tests/Client/Helpers/CustomTestTransport.cs
  tests/Client/Helpers/McpClientFixture.cs
  tests/Client/MockClientTests.cs
  tests/Commands/Server/ToolOperationsTest.cs
Labels: customer-reported, community contribution

#225 Initial Table of contents
  README.md
Labels: documentation

#208 [ONBOARD] Onboard Azure Monitor Health Models #172
  .github/CODEOWNERS
  .vscode/cspell.json
  README.md
  docs/azmcp-commands.md
  src/Arguments/Monitor/HealthModels/Entity/EntityGetHealthArguments.cs
  src/Commands/CommandFactory.cs
  src/Commands/Monitor/HealthModels/BaseMonitorHealthModelsCommand.cs
  src/Commands/Monitor/HealthModels/Entity/EntityGetHealthCommand.cs
  src/Models/Argument/ArgumentDefinitions.cs
  src/Program.cs
  src/Services/Azure/Monitor/MonitorHealthModelService.cs
  src/Services/Interfaces/IMonitorHealthModelService.cs
  tests/Commands/Monitor/HealthModels/Entity/EntityGetHealthCommandTests.cs
Labels: onboarding, area-Health

#198 Support for Azure Redis Cache and Cluster resources
  .github/CODEOWNERS
  .vscode/cspell.json
  CHANGELOG.md
  Directory.Packages.props
  docs/azmcp-commands.md
  infra/services/redis.bicep
  infra/test-resources.bicep
  src/Arguments/Redis/CacheForRedis/AccessPolicyListArguments.cs
  src/Arguments/Redis/CacheForRedis/BaseCacheArguments.cs
  src/Arguments/Redis/CacheForRedis/CacheListArguments.cs
  src/Arguments/Redis/ManagedRedis/BaseClusterArguments.cs
  src/Arguments/Redis/ManagedRedis/ClusterListArguments.cs
  src/Arguments/Redis/ManagedRedis/DatabaseListArguments.cs
  src/AzureMcp.csproj
  src/Commands/CommandFactory.cs
  src/Commands/Redis/CacheForRedis/AccessPolicyListCommand.cs
  src/Commands/Redis/CacheForRedis/BaseCacheCommand.cs
  src/Commands/Redis/CacheForRedis/CacheListCommand.cs
  src/Commands/Redis/ManagedRedis/BaseClusterCommand.cs
  src/Commands/Redis/ManagedRedis/ClusterListCommand.cs
  src/Commands/Redis/ManagedRedis/DatabaseListCommand.cs
  src/Commands/Redis/RedisJsonContext.cs
  src/Models/Argument/ArgumentDefinitions.cs
  src/Models/Redis/CacheForRedis/AccessPolicyAssignment.cs
  src/Models/Redis/CacheForRedis/Cache.cs
  src/Models/Redis/CacheForRedis/CacheConfiguration.cs
  src/Models/Redis/ManagedRedis/Cluster.cs
  src/Models/Redis/ManagedRedis/Database.cs
  src/Models/Redis/ManagedRedis/Module.cs
  src/Program.cs
  src/Services/Azure/Redis/RedisService.cs
  src/Services/Interfaces/IRedisService.cs
  tests/Client/RedisCommandTests.cs
  tests/Commands/Redis/CacheForRedis/AccessPolicyListCommandTests.cs
  tests/Commands/Redis/CacheForRedis/CacheListCommandTests.cs
  tests/Commands/Redis/ManagedRedis/ClusterListCommandTests.cs
  tests/Commands/Redis/ManagedRedis/DatabaseListCommandTests.cs
Labels: onboarding, area-Redis

#268 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation
