Repository Azure/azure-mcp, pull requests merged in 2025-06, with the labels that each got.

#227 Add installation guide video to README
  README.md
Labels: documentation

#300 Add @Azure/azure-mcp as backup owner to all tools
  .github/CODEOWNERS
Labels: Central-EngSys

#301 Fixes Docker image
  CHANGELOG.md
  Dockerfile
  global.json
Labels: area-Docker

#321 Update tool ops to handle empty options
  src/Commands/AzureBestPractices/AzureBestPracticesGetCommand.cs
  src/Commands/Server/ToolOperations.cs
Labels: area-BestPractices

#332 Reduce the size of the README
  README.md
Labels: documentation

#342 Fixes empty tool list errors in live tests
  src/Commands/Server/ToolOperations.cs
  tests/Commands/Server/ToolOperationsTest.cs
Labels: test issue

#336 Update changelog for version 0.2.0 release date
  CHANGELOG.md
Labels: documentation

#316 add set server param for postgres
  .vscode/cspell.json
  docs/azmcp-commands.md
  src/Commands/CommandFactory.cs
  src/Commands/Postgres/PostgresJsonContext.cs
  src/Commands/Postgres/Server/SetParamCommand.cs
  src/Models/Option/OptionDefinitions.cs
  src/Options/Postgres/Server/SetParamOptions.cs
  src/Services/Azure/Postgres/PostgresService.cs
  src/Services/Interfaces/IPostgresService.cs
  tests/Commands/Postgres/Server/SetParamCommandTests.cs
Labels: area-Postgres

#359 Update TROUBLESHOOTING.md
  TROUBLESHOOTING.md
Labels: documentation, area-Auth

#364 Update README.md
  README.md
Labels: documentation

#173 Add support for KeyVault Secrets
  CHANGELOG.md
  Directory.Packages.props
  infra/services/keyvault.bicep
  src/AzureMcp.csproj
  src/Commands/CommandFactory.cs
  src/Commands/KeyVault/KeyVaultJsonContext.cs
  src/Commands/KeyVault/Secret/SecretGetCommand.cs
  src/Models/Option/OptionDefinitions.cs
  src/Options/KeyVault/Secret/SecretGetOptions.cs
  src/Services/Azure/KeyVault/KeyVaultService.cs
  src/Services/Interfaces/IKeyVaultService.cs
  tests/Client/KeyVaultCommandTests.cs
  tests/Commands/Server/ToolOperationsTest.cs
Labels: area-KeyVault

#390 Move Key Vault Secrets to 0.2.2
  CHANGELOG.md
Labels: documentation

#372 docs: Add troubleshooting section for MCP 128-tool limitation
  .vscode/cspell.json
  README.md
  TROUBLESHOOTING.md
  docs/images/128-tools-limit-error.png
Labels: documentation, dogfood bug

#378 [Docker] Fix: mcp server can't start without pwsh #377
  Dockerfile
Labels: area-Docker

#431 Update ModelContextProtocol to 0.3.0-preview.1
  CHANGELOG.md
  Directory.Packages.props
  src/Areas/Server/Commands/ProxyToolOperations.cs
  src/Areas/Server/Commands/ToolOperations.cs
  src/Areas/Server/Commands/Tools/AzureProxyTool.cs
  tests/Areas/Storage/UnitTests/Blob/Container/ContainerListCommandTests.cs
  tests/Client/ClientToolTests.cs
  tests/Client/CommandTestsBase.cs
  tests/Client/Helpers/CustomTestTransport.cs
  tests/Client/MockClientTests.cs
  tests/Commands/Server/ProxyToolOperationsTests.cs
  tests/Commands/Server/Tools/AzureProxyToolTests.cs
Labels: area-Core

#440 Improve Azure Search schema handling including non-retrievable fields, facets, descriptions
  .vscode/cspell.json
  CHANGELOG.md
  README.md
  src/Areas/Search/Commands/Index/IndexDescribeCommand.cs
  src/Areas/Search/Commands/Index/IndexListCommand.cs
  src/Areas/Search/Models/IndexInfo.cs
  src/Areas/Search/Services/ISearchService.cs
  src/Areas/Search/Services/SearchService.cs
  tests/Areas/Search/UnitTests/Index/IndexListCommandTests.cs
Labels: area-Search

#428 Add commands for Azure Platform metrics
  .vscode/cspell.json
  CHANGELOG.md
  README.md
  docs/azmcp-commands.md
  e2eTests/e2eTestPrompts.md
  src/Areas/Monitor/Commands/Metrics/BaseMetricsCommand.cs
  src/Areas/Monitor/Commands/Metrics/MetricsDefinitionsCommand.cs
  src/Areas/Monitor/Commands/Metrics/MetricsQueryCommand.cs
  src/Areas/Monitor/Commands/MonitorJsonContext.cs
  src/Areas/Monitor/Models/MetricDefinition.cs
  src/Areas/Monitor/Models/MetricNamespace.cs
  src/Areas/Monitor/Models/MetricResult.cs
  src/Areas/Monitor/Models/MetricTimeSeries.cs
  src/Areas/Monitor/Models/RoundedDoubleArrayConverter.cs
  src/Areas/Monitor/MonitorSetup.cs
  src/Areas/Monitor/Options/Metrics/BaseMetricsOptions.cs
  src/Areas/Monitor/Options/Metrics/IMetricsOptions.cs
  src/Areas/Monitor/Options/Metrics/MetricsDefinitionsOptions.cs
  src/Areas/Monitor/Options/Metrics/MetricsNamespacesOptions.cs
  src/Areas/Monitor/Options/Metrics/MetricsQueryOptions.cs
  src/Areas/Monitor/Options/MonitorOptionDefinitions.cs
  src/Areas/Monitor/Services/IMetricsQueryClientService.cs
  src/Areas/Monitor/Services/IMonitorMetricsService.cs
  src/Areas/Monitor/Services/IResourceResolverService.cs
  src/Areas/Monitor/Services/MetricsQueryClientService.cs
  src/Areas/Monitor/Services/MonitorMetricsService.cs
  src/Areas/Monitor/Services/ResourceResolverService.cs
  tests/Areas/Monitor/LiveTests/MonitorCommandTests.cs
  tests/Areas/Monitor/UnitTests/Metrics/MetricsDefinitionsCommandTests.cs
  tests/Areas/Monitor/UnitTests/Metrics/MetricsQueryCommandTests.cs
  tests/Areas/Monitor/UnitTests/Metrics/MonitorMetricsServiceTests.cs
  tests/Areas/Monitor/UnitTests/Metrics/ResourceResolverServiceTests.cs
  tests/Areas/Monitor/UnitTests/Models/RoundedDoubleArrayConverterTests.cs
Labels: onboarding, area-Monitor

#435 Fix obsoletion warnings for JsonSerializerOptions.IgnoreNullValues
  Directory.Build.props
  src/Areas/Server/Commands/ProxyToolOperations.cs
  src/Areas/Server/Commands/Tools/AzureProxyTool.cs
Labels: area-Core

#471 Switch tools to return text instead of text resources
  src/Areas/Server/Commands/ToolOperations.cs
  tests/Client/ClientToolTests.cs
  tests/Client/CommandTestsBase.cs
  tests/Client/Helpers/McpTestUtilities.cs
  tests/Client/MockClientTests.cs
Labels: area-Core

#447 Remove unnecessary JsonSchema.Net dependency
  Directory.Packages.props
  src/Areas/Server/Commands/ProxyToolOperations.cs
  src/Areas/Server/Commands/Tools/AzureProxyTool.cs
  src/AzureMcp.csproj
Labels: area-Core
