Repository Azure/azure-mcp, pull requests merged in 2025-07, with the labels that each got.

#492 Add more e2e test prompts to increase coverage
  CHANGELOG.md
  docs/azmcp-commands.md
  e2eTests/e2eTestPrompts.md
  src/Areas/AzureIsv/Commands/Datadog/MonitoredResourcesListCommand.cs
  src/Areas/Kusto/Commands/ClusterListCommand.cs
  src/Areas/Kusto/Commands/DatabaseListCommand.cs
  src/Areas/Kusto/Commands/SampleCommand.cs
  src/Areas/Kusto/Commands/TableListCommand.cs
  src/Areas/Kusto/Commands/TableSchemaCommand.cs
Labels: documentation, test issue

#274 Add model support for AI Foundry
  .github/CODEOWNERS
  .vscode/cspell.json
  CHANGELOG.md
  Directory.Packages.props
  docs/azmcp-commands.md
  infra/services/foundry.bicep
  infra/test-resources.bicep
  src/Areas/Foundry/Commands/FoundryJsonContext.cs
  src/Areas/Foundry/Commands/Models/DeploymentsListCommand.cs
  src/Areas/Foundry/Commands/Models/ModelDeploymentCommand.cs
  src/Areas/Foundry/Commands/Models/ModelsListCommand.cs
  src/Areas/Foundry/FoundrySetup.cs
  src/Areas/Foundry/Models/ModelCatalogFilter.cs
  src/Areas/Foundry/Models/ModelCatalogRequest.cs
  src/Areas/Foundry/Models/ModelCatalogResponse.cs
  src/Areas/Foundry/Models/ModelDeploymentInformation.cs
  src/Areas/Foundry/Models/ModelInformation.cs
  src/Areas/Foundry/Options/FoundryOptionDefinitions.cs
  src/Areas/Foundry/Options/Models/DeploymentsListOptions.cs
  src/Areas/Foundry/Options/Models/ModelDeploymentOptions.cs
  src/Areas/Foundry/Options/Models/ModelsListOptions.cs
  src/Areas/Foundry/Services/FoundryService.cs
  src/Areas/Foundry/Services/IFoundryService.cs
  src/AzureMcp.csproj
  src/Program.cs
  tests/Areas/Foundry/LiveTests/FoundryCommandTests.cs
  tests/Areas/Foundry/UnitTests/DeploymentsListCommandTests.cs
  tests/Areas/Foundry/UnitTests/ModelDeploymentCommandTests.cs
  tests/Areas/Foundry/UnitTests/ModelsListCommandTests.cs
Labels: customer-reported, community contribution, area-Foundry

#500 Fix monitor live tests
  infra/services/monitor.bicep
  infra/test-resources.bicep
  src/Areas/Monitor/Commands/BaseMonitorCommand.cs
  src/Areas/Monitor/Commands/Log/ResourceLogQueryCommand.cs
  src/Areas/Monitor/Commands/Log/WorkspaceLogQueryCommand.cs
  src/Areas/Monitor/Commands/Table/TableListCommand.cs
  src/Areas/Monitor/Options/WorkspaceOptionDefinitions.cs
  src/Areas/Monitor/Options/WorkspaceOptions.cs
  tests/Areas/Monitor/LiveTests/MonitorCommandTests.cs
Labels: test issue, area-Monitor

#289 Add static search resources
  .vscode/cspell.json
  .vscode/launch.json
  eng/scripts/Deploy-TestResources.ps1
  infra/samples/product_info_1.md
  infra/samples/product_info_2.md
  infra/samples/product_info_3.md
  infra/samples/product_info_4.md
  infra/samples/product_info_5.md
  infra/samples/product_info_6.md
  infra/services/search-post.ps1
  infra/services/search.bicep
  infra/test-resources-post.ps1
  infra/test-resources.bicep
  src/Areas/Search/Services/SearchService.cs
  tests/Areas/Search/LiveTests/SearchCommandTests.cs
Labels: Central-EngSys

#610 Add `azmcp sql firewall-rule list` command
  CHANGELOG.md
  README.md
  docs/azmcp-commands.md
  e2eTests/e2eTestPrompts.md
  src/Areas/Sql/Commands/FirewallRule/FirewallRuleListCommand.cs
  src/Areas/Sql/Commands/SqlJsonContext.cs
  src/Areas/Sql/Models/SqlServerFirewallRule.cs
  src/Areas/Sql/Options/FirewallRule/FirewallRuleListOptions.cs
  src/Areas/Sql/Services/ISqlService.cs
  src/Areas/Sql/Services/SqlService.cs
  src/Areas/Sql/SqlSetup.cs
  tests/Areas/Sql/LiveTests/SqlCommandTests.cs
  tests/Areas/Sql/UnitTests/FirewallRule/FirewallRuleListCommandTests.cs
Labels: area-SQL

#661 Azure MCP VSIX Release Job Fixes and Integration
  .vscode/cspell.json
  eng/pipelines/templates/common.yml
  eng/pipelines/templates/jobs/build-vscode.yml
  eng/pipelines/templates/jobs/release.yml
  eng/vscode/ci-package.ps1
Labels: area-Setup

#703 Revise pull request template for clarity and structure
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation

#704 Default to `namespace` mode when `--mode` is not specified
  CHANGELOG.md
  README.md
  TROUBLESHOOTING.md
  docs/azmcp-commands.md
  src/Areas/Server/Commands/ServiceCollectionExtensions.cs
  src/Areas/Server/Commands/ServiceStartCommand.cs
  src/Areas/Server/Options/ModeTypes.cs
  src/Areas/Server/Options/ServiceOptionDefinitions.cs
  src/Areas/Server/Options/ServiceStartOptions.cs
  src/AzureMcp.csproj
  tests/Areas/Server/LiveTests/ServerCommandTests.cs
  tests/Areas/Server/UnitTests/Commands/ServiceCollectionExtensionsTests.cs
  tests/Client/Helpers/LiveTestFixture.cs
Labels: area-Core

#721 Fixes issue where namespace mode does not invoke child MCP server wit…
  src/Areas/Server/Commands/Discovery/CommandGroupServerProvider.cs
  src/Areas/Server/Commands/ToolLoading/ServerToolLoader.cs
  src/Areas/Server/Commands/ToolLoading/SingleProxyToolLoader.cs
  tests/Areas/Server/LiveTests/ServerCommandTests.cs
  tests/Areas/Server/UnitTests/Commands/Discovery/CommandGroupServerProviderTests.cs
Labels: blocking-release

#694 Added Unit Testcases for Group List Command
  tests/Areas/Group/UnitTests/GroupListCommandTests.cs
  tests/Helpers/ResourceGroupTestHelpers.cs
Labels: test issue

#750 Revise README with installation and Docker instructions
  README.md
Labels: documentation

#533 Read AZURE_SUBSCRIPTION_ID from the environment if not provided
  CHANGELOG.md
  areas/monitor/tests/AzureMcp.Monitor.UnitTests/Metrics/MetricsQueryCommandTests.cs
  areas/workbooks/tests/AzureMcp.Workbooks.UnitTests/ListWorkbooksCommandTests.cs
  core/src/AzureMcp.Core/Commands/CommandExtensions.cs
  core/src/AzureMcp.Core/Commands/Subscription/SubscriptionCommand.cs
  core/src/AzureMcp.Core/Models/Option/OptionDefinitions.cs
  core/tests/AzureMcp.Core.UnitTests/Areas/Group/UnitTests/GroupListCommandTests.cs
  core/tests/AzureMcp.Core.UnitTests/Areas/Subscription/SubscriptionCommandTests.cs
  docs/azmcp-commands.md
Labels: area-Auth

#769 Prepare `0.5.1` release
  CHANGELOG.md
  README.md
  docs/azmcp-commands.md
  e2eTests/e2eTestPrompts.md
  eng/vscode/CHANGELOG.md
Labels: documentation
